name: Release & generate artifact

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  deploy:
    uses: alvarogarciapiz/workflows/.github/workflows/release-electron-win.yml@main
    with:
      VERSION: ${{ github.event.release.tag_name }}
    secrets: inherit